services:
  redis:
    image: redis:7-alpine
    container_name: circuit-runners-redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  app:
    build: .
    container_name: circuit-runners-app
    environment:
      - NODE_ENV=production
      - PORT=3000
      - CORS_ORIGIN=${CORS_ORIGIN:-http://localhost}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      - redis

  nginx:
    image: nginx:1.27-alpine
    container_name: circuit-runners-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      # Uncomment 443 mapping if you add TLS (see notes in README)
      # - "443:443"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf:ro
      # For TLS, also mount certs (e.g., from /etc/letsencrypt)
      # - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped

volumes:
  redis-data:
